// File generated by FlutterFire setup / Antigravity assistant.
// To regenerate or link to your Firebase project, run:
// dart pub global run flutterfire_cli:flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Filo application.
///
/// Run `flutterfire configure` to connect your Google / Firebase project
/// and populate actual production credentials.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Placeholder credentials - run `flutterfire configure` to link your Firebase project

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4piLNxgikFehRWhgGWKdInz0nGjrF9I0',
    appId: '1:310049809996:web:347cfad6fd22d7e27876e9',
    messagingSenderId: '310049809996',
    projectId: 'filo-team-dev-2026',
    authDomain: 'filo-team-dev-2026.firebaseapp.com',
    storageBucket: 'filo-team-dev-2026.firebasestorage.app',
    measurementId: 'G-L6VV40CLNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXQtt-lT5ePvvoLY7EsN1_qB8ONaVsfCo',
    appId: '1:310049809996:android:af3f59f7b4a998477876e9',
    messagingSenderId: '310049809996',
    projectId: 'filo-team-dev-2026',
    storageBucket: 'filo-team-dev-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6-faW1re0Kx_X1qFMNWfOS726zI0GbDY',
    appId: '1:310049809996:ios:8e6097ac3ec90cb17876e9',
    messagingSenderId: '310049809996',
    projectId: 'filo-team-dev-2026',
    storageBucket: 'filo-team-dev-2026.firebasestorage.app',
    iosBundleId: 'com.example.filoApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemo-filo-macos-placeholder-api-key',
    appId: '1:100000000000:ios:abcdef1234567890',
    messagingSenderId: '100000000000',
    projectId: 'filo-lms-app',
    storageBucket: 'filo-lms-app.appspot.com',
    iosBundleId: 'com.example.filoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemo-filo-win-placeholder-api-key',
    appId: '1:100000000000:web:abcdef1234567890',
    messagingSenderId: '100000000000',
    projectId: 'filo-lms-app',
    authDomain: 'filo-lms-app.firebaseapp.com',
    storageBucket: 'filo-lms-app.appspot.com',
  );
}
